apiVersion: v1
kind: Pod
metadata:
  name: fortune
  labels:
    app: fortune # label value
spec:
  containers:
    - name: html-generator
      image: luksa/fortune
      volumeMounts:
        - name: html # The volume called html is mounted at /var/htdocs in the container
          mountPath: /var/htdocs
    - name: web-server
      image: nginx:alpine
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: html # The volume called html is mounted at /usr/share/nginx/html in the container
          mountPath: /usr/share/nginx/html
          readOnly: true
  volumes: # define volumes
    - name: html # name of the volume
      emptyDir: {} # define type as emptyDir
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-service
  labels:
    app: fortune
spec:
  type: ClusterIP
  selector:
    app: fortune
  ports:
    - port: 80
      targetPort: 80