# Use the official Nginx image from the Docker Hub
FROM nginx:latest

# Copy custom configuration file (if needed)
# COPY nginx.conf /etc/nginx/nginx.conf

# Copy static files to the Nginx html directory
# COPY ./html /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]